# Docker Compose para DESENVOLVIMENTO
# Use este arquivo durante o desenvolvimento para ter hot-reload

services:
  # Apenas o banco de dados no Docker
  # A aplicação roda localmente com 'npm run start:dev'
  database:
    image: postgres:15-alpine
    container_name: aupus-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: aupus_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # PgAdmin para gerenciar o banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: aupus-pgadmin-dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aupus.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - database
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin

volumes:
  postgres_dev_data:
    driver: local
  pgadmin_dev_data:
    driver: local